version: 2.1

jobs:
  linting:
    docker:
      - image: python:3.7.3-stretch
    working_directory: /Capstone
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv devops
            . devops/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./devops
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run lint
          command: |
            . devops/bin/activate
            make lint

#  build-image:

#  deploy-image:

workflows:
  revisions:
    jobs:
      - linting
#      - build-image:
#          requires: [linting]
#      - deploy-image:
#          requires: [build-image]

